services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
#      - ./migr-postgresql.conf:/etc/postgresql/postgresql.conf
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=openupgrade13
      - RUNNING_ENV=dev
      - LIMIT_TIME_CPU=6000000
      - LIMIT_TIME_REAL=12000000
      - LIMIT_MEMORY_SOFT=5147483648
      - LIMIT_MEMORY_HARD=5684354560
    depends_on:
      - db
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    labels:
      traefik.enable: true
      traefik.longpolling.frontend.rule: "Host:migration.dy;PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:migration.dy"
      docky.main.service: true
      docky.user: odoo

version: '3'
